In [3]:
import tensorflow as tf
import numpy as np

In [4]:
_ = tf.Variable([
    [[1.0, 2, 3], [4, 5, 6]], 
    [[1, 1, 1], [2, 2, 2]], 
    [[3, 2, 1],[6, 5, 4]]
                ])
print("Output of static rnn:", _)  # time_steps * bsz * embed_sz

_trans = tf.transpose(tf.stack(_, axis=0), perm=[1, 0, 2])  # (bsz, time_steps, embed_sz)
print("Trans:", _trans)

bsz = 2
time_steps = 3

query_embeds = tf.cast(tf.Variable([[1.0, 2, 3], [2, 2, 2]]), tf.float32)

S_len = tf.Variable([2, 3])


a = tf.reduce_sum(_trans[0][:S_len[0]] * query_embeds[0], axis=1)
b = tf.nn.softmax(a, axis=0)
c = tf.expand_dims(b, 1) * _trans[0][:S_len[0]]
d = tf.reduce_sum(c, axis=0)

# vv = tf.stack([tf.reduce_sum(tf.expand_dims(tf.nn.softmax(tf.reduce_sum(_trans[i][:S_len[i]] * query_embeds[i], axis=1), axis=0)
#                                    , 1) * _trans[i][:S_len[i]], axis=0) for i in range(bsz)])

# print("vv:", vv)



Output of static rnn: <tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=float32_ref>
Trans: Tensor("transpose:0", shape=(2, 3, 3), dtype=float32)


In [5]:
k = tf.Variable([[1, 2, 3.0], [4, 5, 6]])
kk = tf.nn.softmax(logits=k)
kkk = tf.argmax(kk, 1)
print(kk)

Tensor("Softmax_1:0", shape=(2, 3), dtype=float32)


In [6]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
#     print("vv:", sess.run(vv))
    print(sess.run(kk))
    print(sess.run(kkk))

[14.  6.]
[9.9966466e-01 3.3535014e-04]
[[9.9966466e-01 1.9993293e+00 2.9989939e+00]
 [3.3535014e-04 3.3535014e-04 3.3535014e-04]]
[1.        1.9996647 2.9993293]
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]
[2 2]


In [7]:
a = tf.placeholder(dtype=tf.float32)
print(a)

Tensor("Placeholder:0", dtype=float32)


In [8]:
a = [[1, 2],[4, 5], "a", [3, 4]]
b = a.split("a")

AttributeError: 'list' object has no attribute 'split'

In [18]:
a = tf.Variable([[[1, 1], [2, 2], [3, 3]], [[4,4], [5,5], [6,6]]])  # (bsz, candidates_num, embed_sz)
print(a)
b = tf.Variable([[1, 2], [3, 4]])  # (bsz, embed_sz)
print(b)
b = tf.expand_dims(b, axis=1)
print(b)
c = a*b
print(c)

<tf.Variable 'Variable_18:0' shape=(2, 3, 2) dtype=int32_ref>
<tf.Variable 'Variable_19:0' shape=(2, 2) dtype=int32_ref>
Tensor("ExpandDims_3:0", shape=(2, 1, 2), dtype=int32)
Tensor("mul_4:0", shape=(2, 3, 2), dtype=int32)
