# TF数据产生

下面介绍一些TF产生数据的方法。

## TF初始化器

对于建立`tf.get_variable()`op，可以使用`tf.initializers`来作为初始化器，下面介绍常用的初始化器:

- `tf.initializers.ones()`: 生成初始化为1的张量的初始化器;
- `tf.initializers.zeros()`: 生成初始化为0的张量的初始化器;
- `tf.initializers.random_normal(mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`: 用正态分布产生张量的初始化器;
- `tf.initializers.truncated_normal(mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`: 生成截断正态分布的初始化器;
- `tf.initializers.random_uniform(minval=0, maxval=None, dtype=tf.float32, seed=None)`: 生成具有均匀分布的张量的初始化器;
- `tf.initializers.glorot_normal(seed=None,dtype=tf.float32)`：生成具有Xavier正态分布的初始化器；
- `tf.initializers.glorot_uniform(seed=None,dtype=tf.float32)`: 生成具有Xavier均匀分布的初始化器；

In [47]:
import tensorflow as tf

with tf.variable_scope("test", reuse=tf.AUTO_REUSE) as scope:
    ones_initializer = tf.initializers.ones()
    zeros_initializer = tf.initializers.zeros()
    normal_initializer = tf.initializers.random_normal(mean=0, stddev=1, dtype=tf.float32)
    truncated_initializer = tf.initializers.truncated_normal(mean=0,stddev=1, dtype=tf.float32)
    uniform_initializer = tf.initializers.random_uniform(minval=0, maxval=100, dtype=tf.float32)
    xavier_init = tf.keras.initializers.glorot_uniform() # 有些版本暂时不支持tf.initializers.glorot_uniform
    
    a = tf.get_variable(name="a", shape=(2, 3), initializer=ones_initializer)
    b = tf.get_variable(name="b", shape=(2, 3), initializer=zeros_initializer)
    c = tf.get_variable(name="c", shape=(2, 3), initializer=normal_initializer)
    d = tf.get_variable(name="d", shape=(2, 3), initializer=uniform_initializer)
    e = tf.get_variable(name="e", shape=(2, 3), initializer=truncated_initializer)
    f = tf.get_variable(name="f", shape=(2, 3), initializer=xavier_init)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))
    print(sess.run(f))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 0.07583038  0.3425053  -1.0822985 ]
 [ 1.0452682   0.4481173   0.8941467 ]]
[[0.89619243 0.6311263  0.22577834]
 [0.02859247 0.0621134  0.48102963]]
[[-0.23755573 -0.3566748  -0.4608873 ]
 [-1.7610096   0.22817557  0.00852812]]
[[-0.52205384  0.17615902  0.90402174]
 [-0.31278932 -0.49039662 -0.34612566]]


## TF产生特定分布

在tf中，一般使用如下几个方法产生符合某种分布的数据：

- `tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`：从正态分布中输出shape形状的随机值。
- `tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`: 从截断正态分布中输出shape形状的随机值。
- `tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)`：从均匀分布中输出shape形状的随机值，值的范围为`[minval, maxval)`。
- `tf.random_shuffle(value, seed=None)`：随机打乱一个张量的第一维。
- `tf.set_random_seed(seed)`：设置图级别随机种子。

另外还可以产生poisson，multinomial（多项式），Gamma分布，具体请参考TF官方文档。

In [44]:
a = tf.random_normal(mean=0, stddev=1, shape=(2, 3))
b = tf.truncated_normal(shape=(2, 3))
c = tf.random_uniform(shape=(2, 3))
temp = tf.Variable([[2, 3], [4, 5]], name="temp", dtype=tf.float32)
d = tf.random_shuffle(temp)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(temp))
    print(sess.run(d))

[[-1.0986747   2.084079   -0.20221731]
 [-0.64925593  0.41496274 -0.84865934]]
[[ 0.62663805 -0.84628063 -0.87217516]
 [ 0.23147689 -1.9388355   1.3562949 ]]
[[0.44917202 0.05366623 0.92172146]
 [0.4323541  0.89421785 0.11429787]]
[[2. 3.]
 [4. 5.]]
[[2. 3.]
 [4. 5.]]
