# Tensorflow Tensor Ops

介绍tf中跟tensor操作有关的函数。

In [14]:
import tensorflow as tf
tf.InteractiveSession()
init=tf.global_variables_initializer()
init.run()

/Users/niudong/workon_home/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


### [tf.concat()]((https://www.tensorflow.org/api_docs/python/tf/concat))

可以**在某个维度上连接两个Tensor**，其函数原型为：

```bash
tf.concat(
    values,
    axis,
    name='concat'
)
```

- `values`: 一个Tensor列表或元组，比如：`[Tensor1, Tensor2]`表示要连接这两个`Tensor`;
- `axis`: 想在哪一维度上做连接;

实际上本函数操作表现为**对应维度的拼接**，使用例子如下：

In [3]:
t1 = [[[1, 2], [2, 3]], [[4, 4], [5, 3]]]  # shape=(2, 2, 2)
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]  # shape=(2, 2, 2)

_axis = 1  # 改变这个值查看效果

# 第_axis维上拼接
res_op = tf.concat([t1, t2], axis=_axis)  
print(res_op.eval())

[[[ 1  2]
  [ 2  3]
  [ 7  4]
  [ 8  4]]

 [[ 4  4]
  [ 5  3]
  [ 2 10]
  [15 11]]]


### [tf.transpose](https://www.tensorflow.org/api_docs/python/tf/transpose)

对张量中的维度进行调换，当张量为2维，相当于转置。其函数原型为：

```bash
tf.transpose(
    a,
    perm=None,
    name='transpose',
    conjugate=False
)
```

- `a`: 希望进行调整的张量。
- `perm`: 调整后的维度排列，默认值为`[n-1, ...,0]`。
- `conjugate`: 是否进行共轭变化，当置为`True`且`a`张量是复数类型的时候，会对`a`进行共轭转置。

下面有一种`transpose`的使用的场景：

```python
# Assume features is of size [N, H, W, C] (batch_size, height, width, channels).
# Transpose it to [N, C, H, W], then reshape to [N * C, H * W].
features = tf.reshape(tf.transpose(features, [0, 3, 1, 2]), [N * C, H * W])
```

下面给出了具体的使用例子：

In [17]:
# 简单例子
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y = tf.transpose(x)
print(y.eval())
print()

y = tf.transpose(x, perm=[1, 0])  # 跟上面效果一样
print(y.eval())
print()

# 复杂例子
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])  # shape is (2, 2, 3)
y = tf.transpose(x, perm=[0, 2, 1])  # 将1,2维转置，shape is (2, 3, 2)
print(y.eval())

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


### [tf.convert_to_tensor()](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

将一个非Tensor数据值转化为`Tensor`类型。 其函数原型为:

```bash
tf.convert_to_tensor(
    value,
    dtype=None,
    name=None,
    preferred_dtype=None
)
```

- `value`: 任意一个python类型的数据值；
- `dtype`: 建立的tensor的数据类型,如果缺失将会根据原始值进行推测；
- `preferred_dtype`: `dtype`是`None`的时候使用；

使用例子如下:


In [5]:
a = [[1.0, 2.0], [3.0, 4.0]]
print(tf.convert_to_tensor(a))

Tensor("Const_2:0", shape=(2, 2), dtype=float32)


### [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast)

转换一个Tensor的数据类型。 其函数原型为:

```bash
tf.cast(
    x,
    dtype,
    name=None
)
```
- `x`: 需要转换的Tensor `x`;
- `dtype`: 需要转化为什么类型;

使用例子如下:

In [15]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
y = tf.cast(x, tf.int32)
print(y)

Tensor("Cast:0", shape=(2,), dtype=int32)
