# Tensorflow Tensor Ops

介绍tf中跟tensor操作有关的函数。

In [22]:
import tensorflow as tf
import numpy as np
tf.InteractiveSession()
init=tf.global_variables_initializer()
init.run()

c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


### [tf.concat()]((https://www.tensorflow.org/api_docs/python/tf/concat))

可以**在某个维度上连接两个Tensor**，其函数原型为：

```bash
tf.concat(
    values,
    axis,
    name='concat'
)
```

- `values`: 一个Tensor列表或元组，比如：`[Tensor1, Tensor2]`表示要连接这两个`Tensor`;
- `axis`: 想在哪一维度上做连接;

实际上本函数操作表现为**对应维度的拼接**，使用例子如下：

In [24]:
t1 = [[[1, 2], [2, 3]], [[4, 4], [5, 3]]]  # shape=(2, 2, 2)
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]  # shape=(2, 2, 2)

_axis = 2  # 改变这个值查看效果

# 第_axis维上拼接
res_op = tf.concat([t1, t2], axis=_axis)  
print(res_op.eval())

[[[ 1  2  7  4]
  [ 2  3  8  4]]

 [[ 4  4  2 10]
  [ 5  3 15 11]]]


### [tf.transpose](https://www.tensorflow.org/api_docs/python/tf/transpose)

对张量中的维度进行调换，当张量为2维，相当于转置。其函数原型为：

```bash
tf.transpose(
    a,
    perm=None,
    name='transpose',
    conjugate=False
)
```

- `a`: 希望进行调整的张量。
- `perm`: 调整后的维度排列，默认值为`[n-1, ...,0]`。
- `conjugate`: 是否进行共轭变化，当置为`True`且`a`张量是复数类型的时候，会对`a`进行共轭转置。

下面有一种`transpose`的使用的场景：

```python
# Assume features is of size [N, H, W, C] (batch_size, height, width, channels).
# Transpose it to [N, C, H, W], then reshape to [N * C, H * W].
features = tf.reshape(tf.transpose(features, [0, 3, 1, 2]), [N * C, H * W])
```

下面给出了具体的使用例子：

In [25]:
# 简单例子
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y = tf.transpose(x)
print(y.eval())
print()

y = tf.transpose(x, perm=[1, 0])  # 跟上面效果一样
print(y.eval())
print()

# 复杂例子
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])  # shape is (2, 2, 3)
y = tf.transpose(x, perm=[0, 2, 1])  # 将1,2维转置，shape is (2, 3, 2)
print(y.eval())

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


### [tf.convert_to_tensor()](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

将一个非Tensor数据值转化为`Tensor`类型。 其函数原型为:

```bash
tf.convert_to_tensor(
    value,
    dtype=None,
    name=None,
    preferred_dtype=None
)
```

- `value`: 任意一个python类型的数据值；
- `dtype`: 建立的tensor的数据类型,如果缺失将会根据原始值进行推测；
- `preferred_dtype`: `dtype`是`None`的时候使用；

使用例子如下:


In [5]:
a = [[1.0, 2.0], [3.0, 4.0]]
print(tf.convert_to_tensor(a))

Tensor("Const_2:0", shape=(2, 2), dtype=float32)


### [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast)

转换一个Tensor的数据类型。 其函数原型为:

```bash
tf.cast(
    x,
    dtype,
    name=None
)
```
- `x`: 需要转换的Tensor `x`;
- `dtype`: 需要转化为什么类型;

使用例子如下:

In [6]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
y = tf.cast(x, tf.int32)
print(y)

Tensor("Cast:0", shape=(2,), dtype=int32)


### [tf.get_variable](https://www.tensorflow.org/api_docs/python/tf/get_variable)

获取一个已经存在的变量或者建立一个新的变量. 这个函数可以配合variable scope进行变量重用. 其函数原型为:
```bash
tf.get_variable(
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=None,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.VariableAggregation.NONE
)
```
- `name`: 一个新的或者已存在的变量名称;
- `shape`: 变量的shape;
- `dtype`: 变量的数据类型;
- `initializer`: 变量初始化器;
- `trainable`: 是否要训练这个变量;

In [7]:
def foo():
    with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
        v = tf.get_variable("v", [1])
    return v
v1 = foo()
v2 = foo()
assert v1 == v2

### [tf.clip_by_value](https://www.tensorflow.org/api_docs/python/tf/clip_by_value)

将tensor剪切到特定的min与max之间. 其原型函数为:
```bash
tf.clip_by_value(
    t,
    clip_value_min,
    clip_value_max,
    name=None
)
```

- `t`: 一个tensor;
- `clip_value_min`: 剪切的最小值;
- `clip_value_max`: 剪切的最大值;

下面给出例子:

In [8]:
a = tf.Variable([3.0, 2.0])
b = tf.clip_by_value(a, 2.5, 2.7)
print(b)

Tensor("clip_by_value:0", shape=(2,), dtype=float32)


### [tf.map_fn](https://www.tensorflow.org/api_docs/python/tf/map_fn)

对`elems`在第0维度展开后组成的每一项运用`fn`函数. 其函数原型为:

```bash
tf.map_fn(
    fn,
    elems,
    dtype=None,
    parallel_iterations=10,
    back_prop=True,
    swap_memory=False,
    infer_shape=True,
    name=None
)
```

- `fn`: 一个处理`elems`展开后组合的每一项的函数, 它的返回值结构应该与`dtype`描述的一样;
- `elems`: 一个或者一组tensor, 它们在第0维度会展开, 并将组合结果传入`fn`进行计算;
- `dtype`: 描述`fn`函数返回结果的结构;

使用例子如下:

In [26]:
# 第一种用法
elems = np.array([1, 2, 3, 4, 5, 6])
squares = tf.map_fn(lambda x: x * x, elems)
print("m1:", squares.eval())

# 第二种用法
elems = (np.array([1, 2, 3]), np.array([-1, 1, -1]))
alternate = tf.map_fn(lambda x: x[0] * x[1], elems, dtype=tf.int64)
print("m21:", alternate.eval())
# 第二种用法
elems = (np.array([[1], [2]]), np.array([[2], [3]]))
alternate = tf.map_fn(lambda x: x[0] * x[1], elems, dtype=tf.int64)
print("m22:", alternate.eval())

# 第三种用法
elems = np.array([1, 2, 3])
alternates = tf.map_fn(lambda x: (x, -x), elems, dtype=(tf.int64, tf.int64))
print("m3:")
print(alternates[0].eval())
print(alternates[1].eval())

m1: [ 1  4  9 16 25 36]


InvalidArgumentError: TensorArray dtype is int64 but Op is trying to write dtype int32.
	 [[Node: map_3/while/TensorArrayWrite/TensorArrayWriteV3 = TensorArrayWriteV3[T=DT_INT32, _class=["loc:@map_3/while/mul"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](map_3/while/TensorArrayWrite/TensorArrayWriteV3/Enter, map_3/while/Identity_1, map_3/while/mul, map_3/while/Identity_2)]]

Caused by op 'map_3/while/TensorArrayWrite/TensorArrayWriteV3', defined at:
  File "C:\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\dongn\workon_home\py3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Python36\Lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Python36\Lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\Python36\Lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "c:\users\dongn\workon_home\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\users\dongn\workon_home\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-e09fcd5e679d>", line 8, in <module>
    alternate = tf.map_fn(lambda x: x[0] * x[1], elems, dtype=tf.int64)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 459, in map_fn
    maximum_iterations=n)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2887, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3201, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 451, in compute
    tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 451, in <listcomp>
    tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 842, in write
    return self._implementation.write(index, value, name=name)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 276, in write
    name=name)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 7963, in tensor_array_write_v3
    flow_in=flow_in, name=name)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "c:\users\dongn\workon_home\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): TensorArray dtype is int64 but Op is trying to write dtype int32.
	 [[Node: map_3/while/TensorArrayWrite/TensorArrayWriteV3 = TensorArrayWriteV3[T=DT_INT32, _class=["loc:@map_3/while/mul"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](map_3/while/TensorArrayWrite/TensorArrayWriteV3/Enter, map_3/while/Identity_1, map_3/while/mul, map_3/while/Identity_2)]]


### [tf.gather](https://www.tensorflow.org/api_docs/python/tf/gather)

根据索引从参数轴上收集切片. 其函数原型为:

```bash
tf.gather(
    params,
    indices,
    validate_indices=None,
    name=None,
    axis=0
)
```
- `params`: A tensor. 从哪个`tensor`上收集值, 其rank不能小于`axis+1`;
- `indices`: A tensor. 在某个轴上收集数据的索引值, 它必须在`[0, params.shape[axis]`的范围内;
- `axis`: A tensor. 在`params`的哪个维度上收集数据, 默认在第0维上收集;

使用例子如下:

In [27]:
# 从默认维度收集值
temp = tf.constant([1, 2, 3, 4])
a = tf.gather(temp, [0, 2])
print(a.eval())

# 从特定维度收集值
temp1 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
a1 =  tf.gather(temp1, [0, 1], axis=1)
print(a1.eval())

[1 3]
[[1 2]
 [5 6]]


### [tf.gradients](https://www.tensorflow.org/api_docs/python/tf/gradients)

计算`ys`张量列表对于`xs`张量列表的偏导数. 其函数原型为:

```bash
tf.gradients(
    ys,
    xs,
    grad_ys=None,
    name='gradients',
    colocate_gradients_with_ops=False,
    gate_gradients=False,
    aggregation_method=None,
    stop_gradients=None
)
```
- `ys`: 一个张量或者张量列表. 
- `xs`: 需要在那个tensor上求偏导, 是一个张量或者张量列表. 如果是列表, `ys`中每个y都要对`x`求偏导并相加或者该`x`位置该有的导数值.
- `grad_ys`: 与`ys`有相同大小的张量或者张量列表, 对于`ys`中每个y都计算梯度.

计算方式如下:

In [28]:
a = tf.constant(0.)
b = a * 2
c = a + b
d = tf.gradients(c, [a, b])
print(d[0].eval(), d[1].eval())

3.0 1.0


### [tf.zeros_like](https://www.tensorflow.org/api_docs/python/tf/zeros_like)

建立跟输入张量`dtype`与`shape`一样但所有元素都是0的张量. 其原型函数为:

```bash
tf.zeros_like(
    tensor,
    dtype=None,
    name=None,
    optimize=True
)
```

- `tensor`: 一个张量;
- `dtype`: 需要修改返回张量的`dtype`;

使用例子如下:

In [29]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
a = tf.zeros_like(tensor) 
print(a.eval())

[[0 0 0]
 [0 0 0]]


### [tf.stop_gradient](https://www.tensorflow.org/api_docs/python/tf/stop_gradient)

在构建计算梯度的op时，此op防止将其输入的贡献考虑在内，其函数原型为：

```bash
tf.stop_gradient(
    input,
    name=None
)
```
- `input`: 输入op，这个op关联的变量不会被最后计算梯度的时候考虑在内。

其使用方式如下：

In [30]:
w1 = tf.Variable(2.0)
w2 = tf.Variable(2.0)

a = tf.multiply(w1, 3.0)
a_stoped = tf.stop_gradient(a)

b = tf.multiply(a_stoped, w2)

grads = tf.gradients(b, xs=[w1, w2])  # w1的梯度为None

print(grads)

[None, <tf.Tensor 'gradients_1/Mul_10_grad/Mul_1:0' shape=() dtype=float32>]


### [tf.placeholder_with_default](https://www.tensorflow.org/api_docs/python/tf/placeholder_with_default)

当没有输入feed的时候，使用`input`参数给的值，其函数原型为：

```bash
tf.placeholder_with_default(
    input,
    shape,
    name=None
)
```

- `input`: feed的默认值

### [tf.multiply](https://www.tensorflow.org/api_docs/python/tf/math/multiply)

实现两个张量元素级别相乘。其原型函数为：

```bash
tf.multiply(
    x,
    y,
    name=None
)
```
- `x`: 一个Tensor；
- `y`: 一个Tensor，需要与`x`同一个type；

注意：相乘最里层维度需要一样。

In [43]:
a = tf.Variable([[1, 2, 3], [1, 2, 3]])
b = tf.Variable([2, 2, 2])
print("a:", a)
print("b:", b)
c = tf.multiply(a, b)
init = tf.global_variables_initializer()
init.run()
print(c.eval())

a: <tf.Variable 'Variable_42:0' shape=(2, 3) dtype=int32_ref>
b: <tf.Variable 'Variable_43:0' shape=(3,) dtype=int32_ref>
[[2 4 6]
 [2 4 6]]


### [tf.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

将两个张量相乘。其原型函数为：

```bash
tf.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    name=None
)
```
- `a`: 一个Tensor，Rank >= 1；
- `b`: 一个Tensor，与`a`有相同的Type与Rank；
- `transpose_a`: 如果为真，a在乘法之前被转置；
- `transpose_b`: 如果为真，b在乘法之前被转置；
- `a_is_sparse`: 如果为真，则将a视为稀疏矩阵；
- `b_is_sparse`: 如果为真，则将b视为稀疏矩阵；

注意：如果a或者b矩阵中有大量的0，可以设置相应的sparse标志为True，这样可以加快运算。

In [52]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=(2, 2, 3))
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=(2, 3, 2))
c = tf.matmul(a, b)
print(c)

Tensor("MatMul_5:0", shape=(2, 2, 2), dtype=int32)
