## Python高级使用

In [19]:
# import track
import numpy as np
import tensorflow as tf
import random

### With块的使用

自定义With块对象需要实现`__enter__`与`__exit__`函数：

- `__enter__()`：在使用with语句时调用，会话管理器在代码块开始前调用，返回值与as后的参数绑定；  
- `__exit__()`：会话管理器在代码块执行完成好后调用，在with语句完成时，对象销毁之前调用，如果with里面的代码块有异常，会把异常类型，异常值，异常跟踪信息分别赋值给函数参数`exc_type`, `exc_val`, `exc_tb`, 没有异常这几个值则都是`None`。

例子代码如下：

In [7]:
class WithTest(object):
    
    def __init__(self, name):
        self.name=name
        
    def __enter__(self):
        print("Entered the with block...")
        # 一般都返回self
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        print("Finished the with block.")

with WithTest('with') as test:
    print("Execting with block...")

Entered the with block...
Execting with block...
Finished the with block.


### numpy与list

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([a, b])
print(c, type(c))

a = tf.constant([[1], [2]])
print(a)

def cal_output(task_out, size0):
    temp = tf.reshape(task_out, (size0, -1, task_out.get_shape()[-1]))
    print(temp)
    temp = tf.reduce_mean(temp, reduction_indices=1)
    print(temp)
    return temp

d = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

temp = cal_output(d, 2)

sess = tf.Session()
print(sess.run(temp))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
Tensor("Const_2:0", shape=(2, 1), dtype=int32)
Tensor("Reshape_1:0", shape=(2, 3, 2), dtype=int32)
Tensor("Mean_1:0", shape=(2, 2), dtype=int32)
[[ 3  4]
 [ 9 10]]


In [29]:
a = tf.constant([[[2, 4], [4, 2]],[[4,3], [5,7]]])
print(a.get_shape())
c = tf.reduce_mean(a, 1)
print()
b = tf.Session()
b.run(c)

(2, 2, 2)



array([[3, 3],
       [4, 5]])