# Numpy函数

介绍了一些numpy中常用的函数.


In [3]:
import numpy as np

### [np.vstack](https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.vstack.html)

在垂直方向上堆叠数组. 其函数原型为:

```bash
numpy.vstack(
    tup=()
)
```

- `tup`: 一组`np.ndarray`类型数据, 这组数据除了第一维外其他维度的`shape`都应该一样；

使用例子如下:

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]]


### [np.diag](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html)

提取对角线元素或通过给定对角线元素生成矩阵. 其函数原型为:

```bash
numpy.diag(
    v,
    k=0
)
```
- `v`: 数组类型.如果v是一个二维数组，返回其第k个对角线的副本;如果是一维,生成一个以该数组为对角线的新矩阵；
- `k`: 主对角线以上的对角线用k>0，主对角线以下的对角线用k<0；

使用方式如下:

In [4]:
# 提取对角线
x = np.arange(9).reshape((3,3))
print("x:")
print(x)
print("k=0:", np.diag(x))
print("k=1:", np.diag(x, k=1))
print("k=-1:", np.diag(x, k=-1))

# 生成矩阵
y = np.array([1, 2, 3])
print("y:")
print(np.diag(y))

x:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
k=0: [0 4 8]
k=1: [1 5]
k=-1: [3 7]
y:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### [np.std](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html)

计算指定维度上的标准差。

标准差计算方式为: .

> $std=\sqrt{\dfrac{1}{N}\sum_{i=1}^N(x_i - x')^2}$， 其中$x'$为均值

其函数原型为:

```bash
numpy.std(
    a,
    axis,
    ...
)
```
- `a`: 需要计算标准差的一个array_like类型的数据；
- `axis`: 在哪个或者哪些维度上面计算标准差, 默认展平所有维度并计算所有元素的标准差；

其使用例子如下:

In [13]:
a = np.array([[1, 2, 3], [3, 4, 5]])
print(np.std(a))
print(np.std(a, axis=0))  # 展开第0维度,将展开后数据叠加求标准差
print(np.std(a, axis=1))

1.2909944487358056
[1. 1. 1.]
[0.81649658 0.81649658]


### [numpy.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html)

计算指定维度上的算术平均数。其函数原型为:

```bash
numpy.mean(
    a,
    axis,
    ...
)
```
- `a`: 需要计算平均数的一个array_like类型的值；
- `axis`: 在哪个或者哪些维度上面计算平均值, 默认展平所有维度并计算所有元素的平均值；

In [16]:
a = np.array([[1, 2, 3], [3, 4, 5]])
print(np.mean(a))
print(np.mean(a, axis=0))  # 展开第0维度,将展开后数据叠加求标准差
print(np.mean(a, axis=1))

3.0
[2. 3. 4.]
[2. 4.]


### [np.maximum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html)

求数组元素的元素级最大值。比较两个数组,选择较大值组合成新的数组返回。函数原型为:

```bash
numpy.maximum(
    x1,
    x2
)
```
- `x1`,`x2`: 要比较的数组,它们必须拥有相同的shape；

使用例子如下:


In [15]:
print(np.maximum([2, 3, 4], [1, 5, 2]))
print(np.maximum(np.eye(2), [0.5, 2]))  # broadcasting

[2 5 4]
[[1.  2. ]
 [0.5 2. ]]


### [np.amin](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.amin.html)

返回一个数组的最小值或者一个轴上的最小值. 其函数原型为:

```bash
numpy.amin(
    a,
    axis
)
```

使用例子如下:

In [14]:
a = np.arange(4).reshape((2, 2))
print("a:", a)
print(np.amin(a))
print(np.amin(a, 1))

a: [[0 1]
 [2 3]]
0
[0 2]
