In [50]:
import tensorflow as tf
import numpy as np

## 生成[0, 1)之间的浮点数

一般使用`np.random.random(size=None)`，下面的其他几个函数也可以达到相似的功能：

- `numpy.random.random_sample(size=None)`
- `numpy.random.ranf(size=None)`
- `numpy.random.sample(size=None)`

In [44]:
print(np.random.random())  
print(np.random.random(size=(2, 2))) 

0.8932957575651361
[[0.70197634 0.43550233]
 [0.64419946 0.36946478]]


## 生成[0, 1)之间的浮点数组

一般使用`numpy.random.rand(d0,d1,…,dn)`，函数根据给定维度生成[0,1)之间的数据。这个函数与`np.random.random()`类似，只是调用方式不太一样。

In [45]:
print(np.random.rand())
print(np.random.rand(3,))
print(np.random.rand(3,2))

0.30596338666039147
[0.64113852 0.78071038 0.00807476]
[[0.66835805 0.90947494]
 [0.42113961 0.23764266]
 [0.61339595 0.07668782]]


## 生成具有标准正态分布的数组

一般使用`numpy.random.randn(d0,d1,…,dn)`，函数返回一个或一组样本，具有标准正态分布（随机变量的期望$\mu$为0，标准差为1）。

In [46]:
print(np.random.randn())
print(np.random.randn(3,))
print(np.random.randn(3,2))

0.17340162490810046
[-0.98972248 -0.32081087  0.75728042]
[[ 1.15374132 -0.19494477]
 [-0.56248599 -0.30063406]
 [-1.03777672 -0.70453755]]


## 生成[Low, high)范围内的整数数组

一般使用`numpy.random.randint(low, high=None, size=None)`，函数返回随机整数，范围区间为[low,high）。high没有填写时，默认生成随机数的范围是[0，low)。

In [52]:
print(np.random.randint(1,size=5)) # 返回[0,1)之间的整数，所以只有0
print(np.random.randint(-5,5,size=(2,2)))

[0 0 0 0 0]
[[ 1 -5]
 [-4 -1]]


## 从给定的一维数组中生成随机数组

一般使用`numpy.random.choice(a, size=None, replace=True, p=None)`，函数从给定的一维数组中生成随机数。a为一维数组类似数据或整数；size为数组维度；replace表示是否有放回地取值。a为整数时，对应的一维数组为np.arange(a)

In [63]:
print(np.random.choice(5, 3))
print(np.random.choice([4, 8, 10], 3))
print(np.random.choice([4, 8, 10], 3, replace=False))

[4 1 1]
[ 4 10  4]
[10  4  8]


## 使随机数据可预测

一般使用`numpy.random.seed()`来控制随机数的可预测性。当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数。

In [113]:
np.random.seed(0)
print(np.random.random())  # 运行每次都生成相同的随机数0.5488135039273248
print(np.random.random())  # 运行每次都生成相同的随机数0.7151893663724195

np.random.seed(0)
print(np.random.random())
print(np.random.random())

0.5488135039273248
0.7151893663724195
0.5488135039273248
0.7151893663724195
